import { useEffect, useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HostFinderModal } from '../components/HostFinder';

export default function Home() {
  const [modalOpen, setModalOpen] = useState(true)

  function handleClose() {
    console.info('closing...');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mini app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Demonstration of the Canvas Host Finder
        </h1>
        <div width="480px">
          <HostFinderModal />
        </div>
      </main>

      <footer className={styles.footer}>
        created by cvk
      </footer>
    </div>
  )
}
